### ISSUE TITLE
Feature Request: List secrets in a specified key vault.

### ISSUE THREAD

**Issue by litan1106** [wapacro/az-keyvault-php#2]
Feature Request: List secrets in a specified key vault.

In the real world scenario, you probably have to work with all secrets in a specified key vault.

https://docs.microsoft.com/en-us/rest/api/keyvault/getsecrets/getsecrets

**Comment by wapacro** [comment]
PR has been merged and package released, thanks for your contribution!
See https://github.com/wapacro/az-keyvault-php/releases/tag/v2.1.0
