### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by Supertimor** [wapacro/az-keyvault-php#9]
Hi,

From my azure app service i m getting this error:

error 7: Failed to connect to 169.254.169.254 port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/metadata/identity/oauth2/token?resource=https%3A%2F%2Fvault.azure.net&api-version=2019-08-01 

So i can't get the token from the AD.
Any idea?

Thanks,

**Comment by wapacro** [comment]
Hi @Supertimor 
I'm not an expert with virtual machines in Azure; I usually work further up the XaaS stack. However, my guesses and suggestions would be as follows:

- Do you have managed identity enabled for your virtual machine?
- Does your VM have a network card attached?
- Is that NIC enabled in the OS, recognized & working?
- Can you reach the IP with a simple ping from the VM?

**Comment by wapacro** [comment]
Hi @Supertimor 
Did you enable a [system-assigned managed identity](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity#add-a-system-assigned-identity) to your app service and tried restarting the app afterwards?

**Comment by IGotNothin** [comment]
I see the same thing. I assigned a system assigned user identity and restarted.  This works on a VM but not on an app service.

**Comment by IGotNothin** [comment]
Actually, nevermind.  The url provided above is what you'd use for a VM, but your code is properly pulling the environment variables as described here https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet#obtain-tokens-for-azure-resources.  Thanks for your work on this!

**Comment by wapacro** [comment]
Closed due to inactivity. Please upgrade to the newest version and reopen if the issue persists.
